### PR TITLE
Add support for configuring proxy settings

### PR DESCRIPTION
**Pull request by jovial**
Change-Id: Ic5130a7512d4a26354bd292b0ab51ab4a9279f0a
(cherry picked from commit e48960ecf20c696b2a623bdfbfa7fa4637ff4588)

### CODE REVIEW

**Review by priteau — CHANGES_REQUESTED** [review]
I think you are missing some calls to the proxy playbook in kayobe/cli/commands.py.

**Comment by markgoddard** [comment]
Nice to see CI catching issues!

**Review by priteau — CHANGES_REQUESTED** [review]
Please add commits 5ede87656c05a95e34369417a660fd1b6d06bbfc and 71eb21a3ddab249fe733b56c5f9b70d2947308a5.

**Comment by jovial** [comment]
> 71eb21a

Done, thanks.

**Review by priteau — APPROVED** [review]

**Pull request merged**
