### PR TITLE
Merge stackhpc yoga

### PR DESCRIPTION
**Pull request by Alex-Welsh**
Syncing scientific openstack yoga with stackhpc/yoga
The most important difference is the `manage_lvm` change which is currently blocking.

### CODE REVIEW

**Comment by g0rgamesh** [comment]
Wouldn't a more surgical precision port of `manage_lvm` make more sense?

**Comment by Alex-Welsh** [comment]
> Wouldn't a more surgical precision port of `manage_lvm` make more sense?

I considered it, but it would also just be nice to get things up to date as well

**Comment by markgoddard** [comment]
Agreed it makes sense to keep these in sync.

**Comment by Alex-Welsh** [comment]
Build succeeded [here](https://gitlab.com/scientific-openstack/infrastructure/kayobe-config/-/jobs/5109472274)

**Review by jovial — APPROVED** [review]

**Pull request merged**
