### PR TITLE
Apply 2024.1 backports from 2023.1

### PR DESCRIPTION
**Pull request by seunghun1ee**
Applied following changes
Commit | Change-Id | Message
0bb98c6f60 I496be412cb536d37e1547bb6f1c54717013b8968 Fix eof newline on hosts.rst docs page
08a62c530c None pep8 fix for baremetal compute register
88286c7d50 I900e3000e492b4eb668815ee6789c9d6e3637c68 Add support for Cumulus NVUE switches
9b2ef290ec I8804bd4647140bc837832a0cb6d8bbf3f8e53ac8 Add support for caso

Followings were not applied as they are already in upstream
Commit | Change-Id | Message
a40cc18caa I4fb67477ff312162e58c4462f94c210efd07b146 Revert "Adds support for custom RabbitMQ configuration."
33dc4f1727 None Merge "Make OVS container build regex independent to OVN"

### CODE REVIEW

**Review by Alex-Welsh — APPROVED** [review]
lgtm

**Review by markgoddard — APPROVED** [review]

**Comment by markgoddard** [comment]
py38 failed: `ERROR: No matching distribution found for ansible<10,>=8`

perhaps ansible v8/9 don't suppose py3.8? Do we need to bump the minimum to 3.9 for caracal? It might make sense anyway because we have 3.9 on RL9 and 3.10 on jammy.

Details on python version support in caracal: https://governance.openstack.org/tc/reference/runtimes/2024.1.html

**Comment by Alex-Welsh** [comment]
> py38 failed: `ERROR: No matching distribution found for ansible<10,>=8`
> 
> perhaps ansible v8/9 don't suppose py3.8? Do we need to bump the minimum to 3.9 for caracal? It might make sense anyway because we have 3.9 on RL9 and 3.10 on jammy.
> 
> Details on python version support in caracal: https://governance.openstack.org/tc/reference/runtimes/2024.1.html

That Ansible>=8 requirement means that kayobe depends on python 3.9-3.11. We would need to drop all the way back to Ansible 6 for 3.8 support.

I had assumed that was by design so made a PR [here](https://github.com/stackhpc/stackhpc-release-train/pull/310) to drop the 3.8 test requirement

https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html

**Comment by seunghun1ee** [comment]
@markgoddard Yes, it failed because of python version. Do we merge this?

**Comment by markgoddard** [comment]
> > py38 failed: `ERROR: No matching distribution found for ansible<10,>=8`
> > perhaps ansible v8/9 don't suppose py3.8? Do we need to bump the minimum to 3.9 for caracal? It might make sense anyway because we have 3.9 on RL9 and 3.10 on jammy.
> > Details on python version support in caracal: https://governance.openstack.org/tc/reference/runtimes/2024.1.html
> 
> That Ansible>=8 requirement means that kayobe depends on python 3.9-3.11. We would need to drop all the way back to Ansible 6 for 3.8 support.
> 
> I had assumed that was by design so made a PR [here](https://github.com/stackhpc/stackhpc-release-train/pull/310) to drop the 3.8 test requirement
> 
> https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html

The issue is that py3.8 jobs will still run and fail, then this will prevent 3.10 jobs from running. We'd need a change to the workflow in the .github repo to prevent the 3.8 jobs from running.

**Review by markgoddard — APPROVED** [review]
CI failures aside, the proposed changes look good.

**Comment by markgoddard** [comment]
Proposed disabling fail-fast for tox runs: https://github.com/stackhpc/.github/pull/43

**Pull request merged**
